### ISSUE TITLE
Similar Scripts

### ISSUE THREAD

**Issue by Razberry314** [UNC0V3R3D/Flipper_Zero-BadUsb#21]
In the "GoodUSB" folder (Flipper_Zero-BadUsb>BadUsb-Collection>Windows_badusb>GoodUSB), there is no clear difference between the "Bloatware_remover" and "Win_Debloater" folders, without going into the scripts. (Also, could you *please* use a consistent naming convention? This hurt to type)

**Comment by UNC0V3R3D** [comment]
Hello,
let me get straight to the point. It's clear that you have a hard time comprehending code, so here's some advice: before you start complaining, try learning how to read code properly. Despite the scripts looking somewhat similar, they are actually downloading completely different PowerShell files. If you want to verify this for yourself, take a moment to click on the link provided in the script. Hopefully, that will help you understand the situation better.

**Comment by Razberry314** [comment]
Just figured I'd let you know.
