### ISSUE TITLE
how do i access information?

### ISSUE THREAD

**Issue by DesperC** [UNC0V3R3D/Flipper_Zero-BadUsb#4]
i ran the keylogger on myself and it got me wondering how to actually access information gathered by any bad usb payload at all. where does this data go and how can i get it back?

**Comment by UNC0V3R3D** [comment]
Hello,

To utilize the keylogger function, you will need to insert your own PowerShell script. There are several scripts available on GitHub. Please note that I am unable to provide keylogger scripts as I cannot assume responsibility for any actions taken with them.

Happy New Year
Unc0v3r3d
