### ISSUE TITLE
StealWifiKeys - Delay problem

### ISSUE THREAD

**Issue by Blu3B3ard** [UNC0V3R3D/Flipper_Zero-BadUsb#7]
Hi. 

I was trying the script StealWifiKeys in Windows 11 and there was a problem about the delay timing, so i could fix this adding this times below: 

```
DELAY 1000
LEFTARROW
ENTER
DELAY 1000
ALT y
DELAY 800
GUI UP
DELAY 700
```

Cheers

**Comment by UNC0V3R3D** [comment]
Hi, the delay is different for every single computer. The faster the computer, the less delay you need. Therefore, everyone has to find out a delay that fit's their pc.
